// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv_top,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=4902664,HLS_SYN_TPT=none,HLS_SYN_MEM=44,HLS_SYN_DSP=10,HLS_SYN_FF=4989,HLS_SYN_LUT=8725,HLS_VERSION=2018_3}" *)

module conv_top (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_data_AWVALID,
        m_axi_data_AWREADY,
        m_axi_data_AWADDR,
        m_axi_data_AWID,
        m_axi_data_AWLEN,
        m_axi_data_AWSIZE,
        m_axi_data_AWBURST,
        m_axi_data_AWLOCK,
        m_axi_data_AWCACHE,
        m_axi_data_AWPROT,
        m_axi_data_AWQOS,
        m_axi_data_AWREGION,
        m_axi_data_AWUSER,
        m_axi_data_WVALID,
        m_axi_data_WREADY,
        m_axi_data_WDATA,
        m_axi_data_WSTRB,
        m_axi_data_WLAST,
        m_axi_data_WID,
        m_axi_data_WUSER,
        m_axi_data_ARVALID,
        m_axi_data_ARREADY,
        m_axi_data_ARADDR,
        m_axi_data_ARID,
        m_axi_data_ARLEN,
        m_axi_data_ARSIZE,
        m_axi_data_ARBURST,
        m_axi_data_ARLOCK,
        m_axi_data_ARCACHE,
        m_axi_data_ARPROT,
        m_axi_data_ARQOS,
        m_axi_data_ARREGION,
        m_axi_data_ARUSER,
        m_axi_data_RVALID,
        m_axi_data_RREADY,
        m_axi_data_RDATA,
        m_axi_data_RLAST,
        m_axi_data_RID,
        m_axi_data_RUSER,
        m_axi_data_RRESP,
        m_axi_data_BVALID,
        m_axi_data_BREADY,
        m_axi_data_BRESP,
        m_axi_data_BID,
        m_axi_data_BUSER,
        m_axi_data1_AWVALID,
        m_axi_data1_AWREADY,
        m_axi_data1_AWADDR,
        m_axi_data1_AWID,
        m_axi_data1_AWLEN,
        m_axi_data1_AWSIZE,
        m_axi_data1_AWBURST,
        m_axi_data1_AWLOCK,
        m_axi_data1_AWCACHE,
        m_axi_data1_AWPROT,
        m_axi_data1_AWQOS,
        m_axi_data1_AWREGION,
        m_axi_data1_AWUSER,
        m_axi_data1_WVALID,
        m_axi_data1_WREADY,
        m_axi_data1_WDATA,
        m_axi_data1_WSTRB,
        m_axi_data1_WLAST,
        m_axi_data1_WID,
        m_axi_data1_WUSER,
        m_axi_data1_ARVALID,
        m_axi_data1_ARREADY,
        m_axi_data1_ARADDR,
        m_axi_data1_ARID,
        m_axi_data1_ARLEN,
        m_axi_data1_ARSIZE,
        m_axi_data1_ARBURST,
        m_axi_data1_ARLOCK,
        m_axi_data1_ARCACHE,
        m_axi_data1_ARPROT,
        m_axi_data1_ARQOS,
        m_axi_data1_ARREGION,
        m_axi_data1_ARUSER,
        m_axi_data1_RVALID,
        m_axi_data1_RREADY,
        m_axi_data1_RDATA,
        m_axi_data1_RLAST,
        m_axi_data1_RID,
        m_axi_data1_RUSER,
        m_axi_data1_RRESP,
        m_axi_data1_BVALID,
        m_axi_data1_BREADY,
        m_axi_data1_BRESP,
        m_axi_data1_BID,
        m_axi_data1_BUSER,
        m_axi_data2_AWVALID,
        m_axi_data2_AWREADY,
        m_axi_data2_AWADDR,
        m_axi_data2_AWID,
        m_axi_data2_AWLEN,
        m_axi_data2_AWSIZE,
        m_axi_data2_AWBURST,
        m_axi_data2_AWLOCK,
        m_axi_data2_AWCACHE,
        m_axi_data2_AWPROT,
        m_axi_data2_AWQOS,
        m_axi_data2_AWREGION,
        m_axi_data2_AWUSER,
        m_axi_data2_WVALID,
        m_axi_data2_WREADY,
        m_axi_data2_WDATA,
        m_axi_data2_WSTRB,
        m_axi_data2_WLAST,
        m_axi_data2_WID,
        m_axi_data2_WUSER,
        m_axi_data2_ARVALID,
        m_axi_data2_ARREADY,
        m_axi_data2_ARADDR,
        m_axi_data2_ARID,
        m_axi_data2_ARLEN,
        m_axi_data2_ARSIZE,
        m_axi_data2_ARBURST,
        m_axi_data2_ARLOCK,
        m_axi_data2_ARCACHE,
        m_axi_data2_ARPROT,
        m_axi_data2_ARQOS,
        m_axi_data2_ARREGION,
        m_axi_data2_ARUSER,
        m_axi_data2_RVALID,
        m_axi_data2_RREADY,
        m_axi_data2_RDATA,
        m_axi_data2_RLAST,
        m_axi_data2_RID,
        m_axi_data2_RUSER,
        m_axi_data2_RRESP,
        m_axi_data2_BVALID,
        m_axi_data2_BREADY,
        m_axi_data2_BRESP,
        m_axi_data2_BID,
        m_axi_data2_BUSER,
        m_axi_data3_AWVALID,
        m_axi_data3_AWREADY,
        m_axi_data3_AWADDR,
        m_axi_data3_AWID,
        m_axi_data3_AWLEN,
        m_axi_data3_AWSIZE,
        m_axi_data3_AWBURST,
        m_axi_data3_AWLOCK,
        m_axi_data3_AWCACHE,
        m_axi_data3_AWPROT,
        m_axi_data3_AWQOS,
        m_axi_data3_AWREGION,
        m_axi_data3_AWUSER,
        m_axi_data3_WVALID,
        m_axi_data3_WREADY,
        m_axi_data3_WDATA,
        m_axi_data3_WSTRB,
        m_axi_data3_WLAST,
        m_axi_data3_WID,
        m_axi_data3_WUSER,
        m_axi_data3_ARVALID,
        m_axi_data3_ARREADY,
        m_axi_data3_ARADDR,
        m_axi_data3_ARID,
        m_axi_data3_ARLEN,
        m_axi_data3_ARSIZE,
        m_axi_data3_ARBURST,
        m_axi_data3_ARLOCK,
        m_axi_data3_ARCACHE,
        m_axi_data3_ARPROT,
        m_axi_data3_ARQOS,
        m_axi_data3_ARREGION,
        m_axi_data3_ARUSER,
        m_axi_data3_RVALID,
        m_axi_data3_RREADY,
        m_axi_data3_RDATA,
        m_axi_data3_RLAST,
        m_axi_data3_RID,
        m_axi_data3_RUSER,
        m_axi_data3_RRESP,
        m_axi_data3_BVALID,
        m_axi_data3_BREADY,
        m_axi_data3_BRESP,
        m_axi_data3_BID,
        m_axi_data3_BUSER
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_M_AXI_DATA_ID_WIDTH = 1;
parameter    C_M_AXI_DATA_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA_DATA_WIDTH = 32;
parameter    C_M_AXI_DATA_AWUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_ARUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_WUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_RUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_BUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_TARGET_ADDR = 0;
parameter    C_M_AXI_DATA_USER_VALUE = 0;
parameter    C_M_AXI_DATA_PROT_VALUE = 0;
parameter    C_M_AXI_DATA_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_DATA1_ID_WIDTH = 1;
parameter    C_M_AXI_DATA1_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA1_DATA_WIDTH = 32;
parameter    C_M_AXI_DATA1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_DATA1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_DATA1_WUSER_WIDTH = 1;
parameter    C_M_AXI_DATA1_RUSER_WIDTH = 1;
parameter    C_M_AXI_DATA1_BUSER_WIDTH = 1;
parameter    C_M_AXI_DATA1_TARGET_ADDR = 0;
parameter    C_M_AXI_DATA1_USER_VALUE = 0;
parameter    C_M_AXI_DATA1_PROT_VALUE = 0;
parameter    C_M_AXI_DATA1_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA2_ID_WIDTH = 1;
parameter    C_M_AXI_DATA2_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA2_DATA_WIDTH = 32;
parameter    C_M_AXI_DATA2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_DATA2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_DATA2_WUSER_WIDTH = 1;
parameter    C_M_AXI_DATA2_RUSER_WIDTH = 1;
parameter    C_M_AXI_DATA2_BUSER_WIDTH = 1;
parameter    C_M_AXI_DATA2_TARGET_ADDR = 0;
parameter    C_M_AXI_DATA2_USER_VALUE = 0;
parameter    C_M_AXI_DATA2_PROT_VALUE = 0;
parameter    C_M_AXI_DATA2_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA3_ID_WIDTH = 1;
parameter    C_M_AXI_DATA3_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA3_DATA_WIDTH = 32;
parameter    C_M_AXI_DATA3_AWUSER_WIDTH = 1;
parameter    C_M_AXI_DATA3_ARUSER_WIDTH = 1;
parameter    C_M_AXI_DATA3_WUSER_WIDTH = 1;
parameter    C_M_AXI_DATA3_RUSER_WIDTH = 1;
parameter    C_M_AXI_DATA3_BUSER_WIDTH = 1;
parameter    C_M_AXI_DATA3_TARGET_ADDR = 0;
parameter    C_M_AXI_DATA3_USER_VALUE = 0;
parameter    C_M_AXI_DATA3_PROT_VALUE = 0;
parameter    C_M_AXI_DATA3_CACHE_VALUE = 3;

parameter C_M_AXI_DATA_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_DATA1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_DATA2_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_DATA3_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_data_AWVALID;
input   m_axi_data_AWREADY;
output  [C_M_AXI_DATA_ADDR_WIDTH - 1:0] m_axi_data_AWADDR;
output  [C_M_AXI_DATA_ID_WIDTH - 1:0] m_axi_data_AWID;
output  [7:0] m_axi_data_AWLEN;
output  [2:0] m_axi_data_AWSIZE;
output  [1:0] m_axi_data_AWBURST;
output  [1:0] m_axi_data_AWLOCK;
output  [3:0] m_axi_data_AWCACHE;
output  [2:0] m_axi_data_AWPROT;
output  [3:0] m_axi_data_AWQOS;
output  [3:0] m_axi_data_AWREGION;
output  [C_M_AXI_DATA_AWUSER_WIDTH - 1:0] m_axi_data_AWUSER;
output   m_axi_data_WVALID;
input   m_axi_data_WREADY;
output  [C_M_AXI_DATA_DATA_WIDTH - 1:0] m_axi_data_WDATA;
output  [C_M_AXI_DATA_WSTRB_WIDTH - 1:0] m_axi_data_WSTRB;
output   m_axi_data_WLAST;
output  [C_M_AXI_DATA_ID_WIDTH - 1:0] m_axi_data_WID;
output  [C_M_AXI_DATA_WUSER_WIDTH - 1:0] m_axi_data_WUSER;
output   m_axi_data_ARVALID;
input   m_axi_data_ARREADY;
output  [C_M_AXI_DATA_ADDR_WIDTH - 1:0] m_axi_data_ARADDR;
output  [C_M_AXI_DATA_ID_WIDTH - 1:0] m_axi_data_ARID;
output  [7:0] m_axi_data_ARLEN;
output  [2:0] m_axi_data_ARSIZE;
output  [1:0] m_axi_data_ARBURST;
output  [1:0] m_axi_data_ARLOCK;
output  [3:0] m_axi_data_ARCACHE;
output  [2:0] m_axi_data_ARPROT;
output  [3:0] m_axi_data_ARQOS;
output  [3:0] m_axi_data_ARREGION;
output  [C_M_AXI_DATA_ARUSER_WIDTH - 1:0] m_axi_data_ARUSER;
input   m_axi_data_RVALID;
output   m_axi_data_RREADY;
input  [C_M_AXI_DATA_DATA_WIDTH - 1:0] m_axi_data_RDATA;
input   m_axi_data_RLAST;
input  [C_M_AXI_DATA_ID_WIDTH - 1:0] m_axi_data_RID;
input  [C_M_AXI_DATA_RUSER_WIDTH - 1:0] m_axi_data_RUSER;
input  [1:0] m_axi_data_RRESP;
input   m_axi_data_BVALID;
output   m_axi_data_BREADY;
input  [1:0] m_axi_data_BRESP;
input  [C_M_AXI_DATA_ID_WIDTH - 1:0] m_axi_data_BID;
input  [C_M_AXI_DATA_BUSER_WIDTH - 1:0] m_axi_data_BUSER;
output   m_axi_data1_AWVALID;
input   m_axi_data1_AWREADY;
output  [C_M_AXI_DATA1_ADDR_WIDTH - 1:0] m_axi_data1_AWADDR;
output  [C_M_AXI_DATA1_ID_WIDTH - 1:0] m_axi_data1_AWID;
output  [7:0] m_axi_data1_AWLEN;
output  [2:0] m_axi_data1_AWSIZE;
output  [1:0] m_axi_data1_AWBURST;
output  [1:0] m_axi_data1_AWLOCK;
output  [3:0] m_axi_data1_AWCACHE;
output  [2:0] m_axi_data1_AWPROT;
output  [3:0] m_axi_data1_AWQOS;
output  [3:0] m_axi_data1_AWREGION;
output  [C_M_AXI_DATA1_AWUSER_WIDTH - 1:0] m_axi_data1_AWUSER;
output   m_axi_data1_WVALID;
input   m_axi_data1_WREADY;
output  [C_M_AXI_DATA1_DATA_WIDTH - 1:0] m_axi_data1_WDATA;
output  [C_M_AXI_DATA1_WSTRB_WIDTH - 1:0] m_axi_data1_WSTRB;
output   m_axi_data1_WLAST;
output  [C_M_AXI_DATA1_ID_WIDTH - 1:0] m_axi_data1_WID;
output  [C_M_AXI_DATA1_WUSER_WIDTH - 1:0] m_axi_data1_WUSER;
output   m_axi_data1_ARVALID;
input   m_axi_data1_ARREADY;
output  [C_M_AXI_DATA1_ADDR_WIDTH - 1:0] m_axi_data1_ARADDR;
output  [C_M_AXI_DATA1_ID_WIDTH - 1:0] m_axi_data1_ARID;
output  [7:0] m_axi_data1_ARLEN;
output  [2:0] m_axi_data1_ARSIZE;
output  [1:0] m_axi_data1_ARBURST;
output  [1:0] m_axi_data1_ARLOCK;
output  [3:0] m_axi_data1_ARCACHE;
output  [2:0] m_axi_data1_ARPROT;
output  [3:0] m_axi_data1_ARQOS;
output  [3:0] m_axi_data1_ARREGION;
output  [C_M_AXI_DATA1_ARUSER_WIDTH - 1:0] m_axi_data1_ARUSER;
input   m_axi_data1_RVALID;
output   m_axi_data1_RREADY;
input  [C_M_AXI_DATA1_DATA_WIDTH - 1:0] m_axi_data1_RDATA;
input   m_axi_data1_RLAST;
input  [C_M_AXI_DATA1_ID_WIDTH - 1:0] m_axi_data1_RID;
input  [C_M_AXI_DATA1_RUSER_WIDTH - 1:0] m_axi_data1_RUSER;
input  [1:0] m_axi_data1_RRESP;
input   m_axi_data1_BVALID;
output   m_axi_data1_BREADY;
input  [1:0] m_axi_data1_BRESP;
input  [C_M_AXI_DATA1_ID_WIDTH - 1:0] m_axi_data1_BID;
input  [C_M_AXI_DATA1_BUSER_WIDTH - 1:0] m_axi_data1_BUSER;
output   m_axi_data2_AWVALID;
input   m_axi_data2_AWREADY;
output  [C_M_AXI_DATA2_ADDR_WIDTH - 1:0] m_axi_data2_AWADDR;
output  [C_M_AXI_DATA2_ID_WIDTH - 1:0] m_axi_data2_AWID;
output  [7:0] m_axi_data2_AWLEN;
output  [2:0] m_axi_data2_AWSIZE;
output  [1:0] m_axi_data2_AWBURST;
output  [1:0] m_axi_data2_AWLOCK;
output  [3:0] m_axi_data2_AWCACHE;
output  [2:0] m_axi_data2_AWPROT;
output  [3:0] m_axi_data2_AWQOS;
output  [3:0] m_axi_data2_AWREGION;
output  [C_M_AXI_DATA2_AWUSER_WIDTH - 1:0] m_axi_data2_AWUSER;
output   m_axi_data2_WVALID;
input   m_axi_data2_WREADY;
output  [C_M_AXI_DATA2_DATA_WIDTH - 1:0] m_axi_data2_WDATA;
output  [C_M_AXI_DATA2_WSTRB_WIDTH - 1:0] m_axi_data2_WSTRB;
output   m_axi_data2_WLAST;
output  [C_M_AXI_DATA2_ID_WIDTH - 1:0] m_axi_data2_WID;
output  [C_M_AXI_DATA2_WUSER_WIDTH - 1:0] m_axi_data2_WUSER;
output   m_axi_data2_ARVALID;
input   m_axi_data2_ARREADY;
output  [C_M_AXI_DATA2_ADDR_WIDTH - 1:0] m_axi_data2_ARADDR;
output  [C_M_AXI_DATA2_ID_WIDTH - 1:0] m_axi_data2_ARID;
output  [7:0] m_axi_data2_ARLEN;
output  [2:0] m_axi_data2_ARSIZE;
output  [1:0] m_axi_data2_ARBURST;
output  [1:0] m_axi_data2_ARLOCK;
output  [3:0] m_axi_data2_ARCACHE;
output  [2:0] m_axi_data2_ARPROT;
output  [3:0] m_axi_data2_ARQOS;
output  [3:0] m_axi_data2_ARREGION;
output  [C_M_AXI_DATA2_ARUSER_WIDTH - 1:0] m_axi_data2_ARUSER;
input   m_axi_data2_RVALID;
output   m_axi_data2_RREADY;
input  [C_M_AXI_DATA2_DATA_WIDTH - 1:0] m_axi_data2_RDATA;
input   m_axi_data2_RLAST;
input  [C_M_AXI_DATA2_ID_WIDTH - 1:0] m_axi_data2_RID;
input  [C_M_AXI_DATA2_RUSER_WIDTH - 1:0] m_axi_data2_RUSER;
input  [1:0] m_axi_data2_RRESP;
input   m_axi_data2_BVALID;
output   m_axi_data2_BREADY;
input  [1:0] m_axi_data2_BRESP;
input  [C_M_AXI_DATA2_ID_WIDTH - 1:0] m_axi_data2_BID;
input  [C_M_AXI_DATA2_BUSER_WIDTH - 1:0] m_axi_data2_BUSER;
output   m_axi_data3_AWVALID;
input   m_axi_data3_AWREADY;
output  [C_M_AXI_DATA3_ADDR_WIDTH - 1:0] m_axi_data3_AWADDR;
output  [C_M_AXI_DATA3_ID_WIDTH - 1:0] m_axi_data3_AWID;
output  [7:0] m_axi_data3_AWLEN;
output  [2:0] m_axi_data3_AWSIZE;
output  [1:0] m_axi_data3_AWBURST;
output  [1:0] m_axi_data3_AWLOCK;
output  [3:0] m_axi_data3_AWCACHE;
output  [2:0] m_axi_data3_AWPROT;
output  [3:0] m_axi_data3_AWQOS;
output  [3:0] m_axi_data3_AWREGION;
output  [C_M_AXI_DATA3_AWUSER_WIDTH - 1:0] m_axi_data3_AWUSER;
output   m_axi_data3_WVALID;
input   m_axi_data3_WREADY;
output  [C_M_AXI_DATA3_DATA_WIDTH - 1:0] m_axi_data3_WDATA;
output  [C_M_AXI_DATA3_WSTRB_WIDTH - 1:0] m_axi_data3_WSTRB;
output   m_axi_data3_WLAST;
output  [C_M_AXI_DATA3_ID_WIDTH - 1:0] m_axi_data3_WID;
output  [C_M_AXI_DATA3_WUSER_WIDTH - 1:0] m_axi_data3_WUSER;
output   m_axi_data3_ARVALID;
input   m_axi_data3_ARREADY;
output  [C_M_AXI_DATA3_ADDR_WIDTH - 1:0] m_axi_data3_ARADDR;
output  [C_M_AXI_DATA3_ID_WIDTH - 1:0] m_axi_data3_ARID;
output  [7:0] m_axi_data3_ARLEN;
output  [2:0] m_axi_data3_ARSIZE;
output  [1:0] m_axi_data3_ARBURST;
output  [1:0] m_axi_data3_ARLOCK;
output  [3:0] m_axi_data3_ARCACHE;
output  [2:0] m_axi_data3_ARPROT;
output  [3:0] m_axi_data3_ARQOS;
output  [3:0] m_axi_data3_ARREGION;
output  [C_M_AXI_DATA3_ARUSER_WIDTH - 1:0] m_axi_data3_ARUSER;
input   m_axi_data3_RVALID;
output   m_axi_data3_RREADY;
input  [C_M_AXI_DATA3_DATA_WIDTH - 1:0] m_axi_data3_RDATA;
input   m_axi_data3_RLAST;
input  [C_M_AXI_DATA3_ID_WIDTH - 1:0] m_axi_data3_RID;
input  [C_M_AXI_DATA3_RUSER_WIDTH - 1:0] m_axi_data3_RUSER;
input  [1:0] m_axi_data3_RRESP;
input   m_axi_data3_BVALID;
output   m_axi_data3_BREADY;
input  [1:0] m_axi_data3_BRESP;
input  [C_M_AXI_DATA3_ID_WIDTH - 1:0] m_axi_data3_BID;
input  [C_M_AXI_DATA3_BUSER_WIDTH - 1:0] m_axi_data3_BUSER;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [10:0] conv_out1_address0;
reg    conv_out1_ce0;
reg    conv_out1_we0;
reg   [31:0] conv_out1_d0;
wire   [31:0] conv_out1_q0;
reg    data_AWVALID;
wire    data_AWREADY;
reg    data_WVALID;
wire    data_WREADY;
reg    data_ARVALID;
wire    data_ARREADY;
wire    data_RVALID;
reg    data_RREADY;
wire   [31:0] data_RDATA;
wire    data_RLAST;
wire   [0:0] data_RID;
wire   [0:0] data_RUSER;
wire   [1:0] data_RRESP;
wire    data_BVALID;
reg    data_BREADY;
wire   [1:0] data_BRESP;
wire   [0:0] data_BID;
wire   [0:0] data_BUSER;
reg    data1_AWVALID;
wire    data1_AWREADY;
reg    data1_WVALID;
wire    data1_WREADY;
reg    data1_ARVALID;
wire    data1_ARREADY;
wire    data1_RVALID;
reg    data1_RREADY;
wire   [31:0] data1_RDATA;
wire    data1_RLAST;
wire   [0:0] data1_RID;
wire   [0:0] data1_RUSER;
wire   [1:0] data1_RRESP;
wire    data1_BVALID;
reg    data1_BREADY;
wire   [1:0] data1_BRESP;
wire   [0:0] data1_BID;
wire   [0:0] data1_BUSER;
wire    data2_AWREADY;
wire    data2_WREADY;
reg    data2_ARVALID;
wire    data2_ARREADY;
reg   [31:0] data2_ARADDR;
reg   [0:0] data2_ARID;
reg   [31:0] data2_ARLEN;
reg   [2:0] data2_ARSIZE;
reg   [1:0] data2_ARBURST;
reg   [1:0] data2_ARLOCK;
reg   [3:0] data2_ARCACHE;
reg   [2:0] data2_ARPROT;
reg   [3:0] data2_ARQOS;
reg   [3:0] data2_ARREGION;
reg   [0:0] data2_ARUSER;
wire    data2_RVALID;
reg    data2_RREADY;
wire   [31:0] data2_RDATA;
wire    data2_RLAST;
wire   [0:0] data2_RID;
wire   [0:0] data2_RUSER;
wire   [1:0] data2_RRESP;
wire    data2_BVALID;
wire   [1:0] data2_BRESP;
wire   [0:0] data2_BID;
wire   [0:0] data2_BUSER;
wire    data3_AWREADY;
wire    data3_WREADY;
reg    data3_ARVALID;
wire    data3_ARREADY;
reg   [31:0] data3_ARADDR;
reg   [0:0] data3_ARID;
reg   [31:0] data3_ARLEN;
reg   [2:0] data3_ARSIZE;
reg   [1:0] data3_ARBURST;
reg   [1:0] data3_ARLOCK;
reg   [3:0] data3_ARCACHE;
reg   [2:0] data3_ARPROT;
reg   [3:0] data3_ARQOS;
reg   [3:0] data3_ARREGION;
reg   [0:0] data3_ARUSER;
wire    data3_RVALID;
reg    data3_RREADY;
wire   [31:0] data3_RDATA;
wire    data3_RLAST;
wire   [0:0] data3_RID;
wire   [0:0] data3_RUSER;
wire   [1:0] data3_RRESP;
wire    data3_BVALID;
wire   [1:0] data3_BRESP;
wire   [0:0] data3_BID;
wire   [0:0] data3_BUSER;
wire    grp_conv1_fu_50_ap_start;
wire    grp_conv1_fu_50_ap_done;
wire    grp_conv1_fu_50_ap_idle;
wire    grp_conv1_fu_50_ap_ready;
wire    grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWVALID;
wire   [31:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWADDR;
wire   [0:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWID;
wire   [31:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWLEN;
wire   [2:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWSIZE;
wire   [1:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWBURST;
wire   [1:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWLOCK;
wire   [3:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWCACHE;
wire   [2:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWPROT;
wire   [3:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWQOS;
wire   [3:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWREGION;
wire   [0:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWUSER;
wire    grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_WVALID;
wire   [31:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_WDATA;
wire   [3:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_WSTRB;
wire    grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_WLAST;
wire   [0:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_WID;
wire   [0:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_WUSER;
wire    grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARVALID;
wire   [31:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARADDR;
wire   [0:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARID;
wire   [31:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARLEN;
wire   [2:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARSIZE;
wire   [1:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARBURST;
wire   [1:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARLOCK;
wire   [3:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARCACHE;
wire   [2:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARPROT;
wire   [3:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARQOS;
wire   [3:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARREGION;
wire   [0:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARUSER;
wire    grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_RREADY;
wire    grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_BREADY;
wire    grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWVALID;
wire   [31:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWADDR;
wire   [0:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWID;
wire   [31:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWLEN;
wire   [2:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWSIZE;
wire   [1:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWBURST;
wire   [1:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWLOCK;
wire   [3:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWCACHE;
wire   [2:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWPROT;
wire   [3:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWQOS;
wire   [3:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWREGION;
wire   [0:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWUSER;
wire    grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WVALID;
wire   [31:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WDATA;
wire   [3:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WSTRB;
wire    grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WLAST;
wire   [0:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WID;
wire   [0:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WUSER;
wire    grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARVALID;
wire   [31:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARADDR;
wire   [0:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARID;
wire   [31:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARLEN;
wire   [2:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARSIZE;
wire   [1:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARBURST;
wire   [1:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARLOCK;
wire   [3:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARCACHE;
wire   [2:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARPROT;
wire   [3:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARQOS;
wire   [3:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARREGION;
wire   [0:0] grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARUSER;
wire    grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_RREADY;
wire    grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_BREADY;
wire    grp_conv1_fu_50_m_axi_WEIGHT_AWVALID;
wire   [31:0] grp_conv1_fu_50_m_axi_WEIGHT_AWADDR;
wire   [0:0] grp_conv1_fu_50_m_axi_WEIGHT_AWID;
wire   [31:0] grp_conv1_fu_50_m_axi_WEIGHT_AWLEN;
wire   [2:0] grp_conv1_fu_50_m_axi_WEIGHT_AWSIZE;
wire   [1:0] grp_conv1_fu_50_m_axi_WEIGHT_AWBURST;
wire   [1:0] grp_conv1_fu_50_m_axi_WEIGHT_AWLOCK;
wire   [3:0] grp_conv1_fu_50_m_axi_WEIGHT_AWCACHE;
wire   [2:0] grp_conv1_fu_50_m_axi_WEIGHT_AWPROT;
wire   [3:0] grp_conv1_fu_50_m_axi_WEIGHT_AWQOS;
wire   [3:0] grp_conv1_fu_50_m_axi_WEIGHT_AWREGION;
wire   [0:0] grp_conv1_fu_50_m_axi_WEIGHT_AWUSER;
wire    grp_conv1_fu_50_m_axi_WEIGHT_WVALID;
wire   [31:0] grp_conv1_fu_50_m_axi_WEIGHT_WDATA;
wire   [3:0] grp_conv1_fu_50_m_axi_WEIGHT_WSTRB;
wire    grp_conv1_fu_50_m_axi_WEIGHT_WLAST;
wire   [0:0] grp_conv1_fu_50_m_axi_WEIGHT_WID;
wire   [0:0] grp_conv1_fu_50_m_axi_WEIGHT_WUSER;
wire    grp_conv1_fu_50_m_axi_WEIGHT_ARVALID;
wire   [31:0] grp_conv1_fu_50_m_axi_WEIGHT_ARADDR;
wire   [0:0] grp_conv1_fu_50_m_axi_WEIGHT_ARID;
wire   [31:0] grp_conv1_fu_50_m_axi_WEIGHT_ARLEN;
wire   [2:0] grp_conv1_fu_50_m_axi_WEIGHT_ARSIZE;
wire   [1:0] grp_conv1_fu_50_m_axi_WEIGHT_ARBURST;
wire   [1:0] grp_conv1_fu_50_m_axi_WEIGHT_ARLOCK;
wire   [3:0] grp_conv1_fu_50_m_axi_WEIGHT_ARCACHE;
wire   [2:0] grp_conv1_fu_50_m_axi_WEIGHT_ARPROT;
wire   [3:0] grp_conv1_fu_50_m_axi_WEIGHT_ARQOS;
wire   [3:0] grp_conv1_fu_50_m_axi_WEIGHT_ARREGION;
wire   [0:0] grp_conv1_fu_50_m_axi_WEIGHT_ARUSER;
wire    grp_conv1_fu_50_m_axi_WEIGHT_RREADY;
wire    grp_conv1_fu_50_m_axi_WEIGHT_BREADY;
wire    grp_conv1_fu_50_m_axi_BIAS_AWVALID;
wire   [31:0] grp_conv1_fu_50_m_axi_BIAS_AWADDR;
wire   [0:0] grp_conv1_fu_50_m_axi_BIAS_AWID;
wire   [31:0] grp_conv1_fu_50_m_axi_BIAS_AWLEN;
wire   [2:0] grp_conv1_fu_50_m_axi_BIAS_AWSIZE;
wire   [1:0] grp_conv1_fu_50_m_axi_BIAS_AWBURST;
wire   [1:0] grp_conv1_fu_50_m_axi_BIAS_AWLOCK;
wire   [3:0] grp_conv1_fu_50_m_axi_BIAS_AWCACHE;
wire   [2:0] grp_conv1_fu_50_m_axi_BIAS_AWPROT;
wire   [3:0] grp_conv1_fu_50_m_axi_BIAS_AWQOS;
wire   [3:0] grp_conv1_fu_50_m_axi_BIAS_AWREGION;
wire   [0:0] grp_conv1_fu_50_m_axi_BIAS_AWUSER;
wire    grp_conv1_fu_50_m_axi_BIAS_WVALID;
wire   [31:0] grp_conv1_fu_50_m_axi_BIAS_WDATA;
wire   [3:0] grp_conv1_fu_50_m_axi_BIAS_WSTRB;
wire    grp_conv1_fu_50_m_axi_BIAS_WLAST;
wire   [0:0] grp_conv1_fu_50_m_axi_BIAS_WID;
wire   [0:0] grp_conv1_fu_50_m_axi_BIAS_WUSER;
wire    grp_conv1_fu_50_m_axi_BIAS_ARVALID;
wire   [31:0] grp_conv1_fu_50_m_axi_BIAS_ARADDR;
wire   [0:0] grp_conv1_fu_50_m_axi_BIAS_ARID;
wire   [31:0] grp_conv1_fu_50_m_axi_BIAS_ARLEN;
wire   [2:0] grp_conv1_fu_50_m_axi_BIAS_ARSIZE;
wire   [1:0] grp_conv1_fu_50_m_axi_BIAS_ARBURST;
wire   [1:0] grp_conv1_fu_50_m_axi_BIAS_ARLOCK;
wire   [3:0] grp_conv1_fu_50_m_axi_BIAS_ARCACHE;
wire   [2:0] grp_conv1_fu_50_m_axi_BIAS_ARPROT;
wire   [3:0] grp_conv1_fu_50_m_axi_BIAS_ARQOS;
wire   [3:0] grp_conv1_fu_50_m_axi_BIAS_ARREGION;
wire   [0:0] grp_conv1_fu_50_m_axi_BIAS_ARUSER;
wire    grp_conv1_fu_50_m_axi_BIAS_RREADY;
wire    grp_conv1_fu_50_m_axi_BIAS_BREADY;
wire   [10:0] grp_conv1_fu_50_conv_out1_address0;
wire    grp_conv1_fu_50_conv_out1_ce0;
wire    grp_conv1_fu_50_conv_out1_we0;
wire   [31:0] grp_conv1_fu_50_conv_out1_d0;
wire    grp_conv2_fu_72_ap_start;
wire    grp_conv2_fu_72_ap_done;
wire    grp_conv2_fu_72_ap_idle;
wire    grp_conv2_fu_72_ap_ready;
wire    grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWVALID;
wire   [31:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWADDR;
wire   [0:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWID;
wire   [31:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWLEN;
wire   [2:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWSIZE;
wire   [1:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWBURST;
wire   [1:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWLOCK;
wire   [3:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWCACHE;
wire   [2:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWPROT;
wire   [3:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWQOS;
wire   [3:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWREGION;
wire   [0:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWUSER;
wire    grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WVALID;
wire   [31:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WDATA;
wire   [3:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WSTRB;
wire    grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WLAST;
wire   [0:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WID;
wire   [0:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WUSER;
wire    grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARVALID;
wire   [31:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARADDR;
wire   [0:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARID;
wire   [31:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARLEN;
wire   [2:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARSIZE;
wire   [1:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARBURST;
wire   [1:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARLOCK;
wire   [3:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARCACHE;
wire   [2:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARPROT;
wire   [3:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARQOS;
wire   [3:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARREGION;
wire   [0:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARUSER;
wire    grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_RREADY;
wire    grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_BREADY;
wire    grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWVALID;
wire   [31:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWADDR;
wire   [0:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWID;
wire   [31:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWLEN;
wire   [2:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWSIZE;
wire   [1:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWBURST;
wire   [1:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWLOCK;
wire   [3:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWCACHE;
wire   [2:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWPROT;
wire   [3:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWQOS;
wire   [3:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWREGION;
wire   [0:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWUSER;
wire    grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_WVALID;
wire   [31:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_WDATA;
wire   [3:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_WSTRB;
wire    grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_WLAST;
wire   [0:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_WID;
wire   [0:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_WUSER;
wire    grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARVALID;
wire   [31:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARADDR;
wire   [0:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARID;
wire   [31:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARLEN;
wire   [2:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARSIZE;
wire   [1:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARBURST;
wire   [1:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARLOCK;
wire   [3:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARCACHE;
wire   [2:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARPROT;
wire   [3:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARQOS;
wire   [3:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARREGION;
wire   [0:0] grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARUSER;
wire    grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_RREADY;
wire    grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_BREADY;
wire    grp_conv2_fu_72_m_axi_WEIGHT_AWVALID;
wire   [31:0] grp_conv2_fu_72_m_axi_WEIGHT_AWADDR;
wire   [0:0] grp_conv2_fu_72_m_axi_WEIGHT_AWID;
wire   [31:0] grp_conv2_fu_72_m_axi_WEIGHT_AWLEN;
wire   [2:0] grp_conv2_fu_72_m_axi_WEIGHT_AWSIZE;
wire   [1:0] grp_conv2_fu_72_m_axi_WEIGHT_AWBURST;
wire   [1:0] grp_conv2_fu_72_m_axi_WEIGHT_AWLOCK;
wire   [3:0] grp_conv2_fu_72_m_axi_WEIGHT_AWCACHE;
wire   [2:0] grp_conv2_fu_72_m_axi_WEIGHT_AWPROT;
wire   [3:0] grp_conv2_fu_72_m_axi_WEIGHT_AWQOS;
wire   [3:0] grp_conv2_fu_72_m_axi_WEIGHT_AWREGION;
wire   [0:0] grp_conv2_fu_72_m_axi_WEIGHT_AWUSER;
wire    grp_conv2_fu_72_m_axi_WEIGHT_WVALID;
wire   [31:0] grp_conv2_fu_72_m_axi_WEIGHT_WDATA;
wire   [3:0] grp_conv2_fu_72_m_axi_WEIGHT_WSTRB;
wire    grp_conv2_fu_72_m_axi_WEIGHT_WLAST;
wire   [0:0] grp_conv2_fu_72_m_axi_WEIGHT_WID;
wire   [0:0] grp_conv2_fu_72_m_axi_WEIGHT_WUSER;
wire    grp_conv2_fu_72_m_axi_WEIGHT_ARVALID;
wire   [31:0] grp_conv2_fu_72_m_axi_WEIGHT_ARADDR;
wire   [0:0] grp_conv2_fu_72_m_axi_WEIGHT_ARID;
wire   [31:0] grp_conv2_fu_72_m_axi_WEIGHT_ARLEN;
wire   [2:0] grp_conv2_fu_72_m_axi_WEIGHT_ARSIZE;
wire   [1:0] grp_conv2_fu_72_m_axi_WEIGHT_ARBURST;
wire   [1:0] grp_conv2_fu_72_m_axi_WEIGHT_ARLOCK;
wire   [3:0] grp_conv2_fu_72_m_axi_WEIGHT_ARCACHE;
wire   [2:0] grp_conv2_fu_72_m_axi_WEIGHT_ARPROT;
wire   [3:0] grp_conv2_fu_72_m_axi_WEIGHT_ARQOS;
wire   [3:0] grp_conv2_fu_72_m_axi_WEIGHT_ARREGION;
wire   [0:0] grp_conv2_fu_72_m_axi_WEIGHT_ARUSER;
wire    grp_conv2_fu_72_m_axi_WEIGHT_RREADY;
wire    grp_conv2_fu_72_m_axi_WEIGHT_BREADY;
wire    grp_conv2_fu_72_m_axi_BIAS_AWVALID;
wire   [31:0] grp_conv2_fu_72_m_axi_BIAS_AWADDR;
wire   [0:0] grp_conv2_fu_72_m_axi_BIAS_AWID;
wire   [31:0] grp_conv2_fu_72_m_axi_BIAS_AWLEN;
wire   [2:0] grp_conv2_fu_72_m_axi_BIAS_AWSIZE;
wire   [1:0] grp_conv2_fu_72_m_axi_BIAS_AWBURST;
wire   [1:0] grp_conv2_fu_72_m_axi_BIAS_AWLOCK;
wire   [3:0] grp_conv2_fu_72_m_axi_BIAS_AWCACHE;
wire   [2:0] grp_conv2_fu_72_m_axi_BIAS_AWPROT;
wire   [3:0] grp_conv2_fu_72_m_axi_BIAS_AWQOS;
wire   [3:0] grp_conv2_fu_72_m_axi_BIAS_AWREGION;
wire   [0:0] grp_conv2_fu_72_m_axi_BIAS_AWUSER;
wire    grp_conv2_fu_72_m_axi_BIAS_WVALID;
wire   [31:0] grp_conv2_fu_72_m_axi_BIAS_WDATA;
wire   [3:0] grp_conv2_fu_72_m_axi_BIAS_WSTRB;
wire    grp_conv2_fu_72_m_axi_BIAS_WLAST;
wire   [0:0] grp_conv2_fu_72_m_axi_BIAS_WID;
wire   [0:0] grp_conv2_fu_72_m_axi_BIAS_WUSER;
wire    grp_conv2_fu_72_m_axi_BIAS_ARVALID;
wire   [31:0] grp_conv2_fu_72_m_axi_BIAS_ARADDR;
wire   [0:0] grp_conv2_fu_72_m_axi_BIAS_ARID;
wire   [31:0] grp_conv2_fu_72_m_axi_BIAS_ARLEN;
wire   [2:0] grp_conv2_fu_72_m_axi_BIAS_ARSIZE;
wire   [1:0] grp_conv2_fu_72_m_axi_BIAS_ARBURST;
wire   [1:0] grp_conv2_fu_72_m_axi_BIAS_ARLOCK;
wire   [3:0] grp_conv2_fu_72_m_axi_BIAS_ARCACHE;
wire   [2:0] grp_conv2_fu_72_m_axi_BIAS_ARPROT;
wire   [3:0] grp_conv2_fu_72_m_axi_BIAS_ARQOS;
wire   [3:0] grp_conv2_fu_72_m_axi_BIAS_ARREGION;
wire   [0:0] grp_conv2_fu_72_m_axi_BIAS_ARUSER;
wire    grp_conv2_fu_72_m_axi_BIAS_RREADY;
wire    grp_conv2_fu_72_m_axi_BIAS_BREADY;
wire   [10:0] grp_conv2_fu_72_conv_out1_address0;
wire    grp_conv2_fu_72_conv_out1_ce0;
wire    grp_conv2_fu_72_conv_out1_we0;
wire   [31:0] grp_conv2_fu_72_conv_out1_d0;
reg    grp_conv1_fu_50_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_conv2_fu_72_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_conv1_fu_50_ap_start_reg = 1'b0;
#0 grp_conv2_fu_72_ap_start_reg = 1'b0;
end

conv_top_conv_out1 #(
    .DataWidth( 32 ),
    .AddressRange( 1176 ),
    .AddressWidth( 11 ))
conv_out1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(conv_out1_address0),
    .ce0(conv_out1_ce0),
    .we0(conv_out1_we0),
    .d0(conv_out1_d0),
    .q0(conv_out1_q0)
);

conv_top_data_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_DATA_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_DATA_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_DATA_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_DATA_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_DATA_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_DATA_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_DATA_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_DATA_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_DATA_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_DATA_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_DATA_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_DATA_CACHE_VALUE ))
conv_top_data_m_axi_U(
    .AWVALID(m_axi_data_AWVALID),
    .AWREADY(m_axi_data_AWREADY),
    .AWADDR(m_axi_data_AWADDR),
    .AWID(m_axi_data_AWID),
    .AWLEN(m_axi_data_AWLEN),
    .AWSIZE(m_axi_data_AWSIZE),
    .AWBURST(m_axi_data_AWBURST),
    .AWLOCK(m_axi_data_AWLOCK),
    .AWCACHE(m_axi_data_AWCACHE),
    .AWPROT(m_axi_data_AWPROT),
    .AWQOS(m_axi_data_AWQOS),
    .AWREGION(m_axi_data_AWREGION),
    .AWUSER(m_axi_data_AWUSER),
    .WVALID(m_axi_data_WVALID),
    .WREADY(m_axi_data_WREADY),
    .WDATA(m_axi_data_WDATA),
    .WSTRB(m_axi_data_WSTRB),
    .WLAST(m_axi_data_WLAST),
    .WID(m_axi_data_WID),
    .WUSER(m_axi_data_WUSER),
    .ARVALID(m_axi_data_ARVALID),
    .ARREADY(m_axi_data_ARREADY),
    .ARADDR(m_axi_data_ARADDR),
    .ARID(m_axi_data_ARID),
    .ARLEN(m_axi_data_ARLEN),
    .ARSIZE(m_axi_data_ARSIZE),
    .ARBURST(m_axi_data_ARBURST),
    .ARLOCK(m_axi_data_ARLOCK),
    .ARCACHE(m_axi_data_ARCACHE),
    .ARPROT(m_axi_data_ARPROT),
    .ARQOS(m_axi_data_ARQOS),
    .ARREGION(m_axi_data_ARREGION),
    .ARUSER(m_axi_data_ARUSER),
    .RVALID(m_axi_data_RVALID),
    .RREADY(m_axi_data_RREADY),
    .RDATA(m_axi_data_RDATA),
    .RLAST(m_axi_data_RLAST),
    .RID(m_axi_data_RID),
    .RUSER(m_axi_data_RUSER),
    .RRESP(m_axi_data_RRESP),
    .BVALID(m_axi_data_BVALID),
    .BREADY(m_axi_data_BREADY),
    .BRESP(m_axi_data_BRESP),
    .BID(m_axi_data_BID),
    .BUSER(m_axi_data_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(data_ARVALID),
    .I_ARREADY(data_ARREADY),
    .I_ARADDR(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARADDR),
    .I_ARID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARID),
    .I_ARLEN(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARLEN),
    .I_ARSIZE(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARSIZE),
    .I_ARLOCK(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARLOCK),
    .I_ARCACHE(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARCACHE),
    .I_ARQOS(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARQOS),
    .I_ARPROT(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARPROT),
    .I_ARUSER(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARUSER),
    .I_ARBURST(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARBURST),
    .I_ARREGION(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARREGION),
    .I_RVALID(data_RVALID),
    .I_RREADY(data_RREADY),
    .I_RDATA(data_RDATA),
    .I_RID(data_RID),
    .I_RUSER(data_RUSER),
    .I_RRESP(data_RRESP),
    .I_RLAST(data_RLAST),
    .I_AWVALID(data_AWVALID),
    .I_AWREADY(data_AWREADY),
    .I_AWADDR(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWADDR),
    .I_AWID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWID),
    .I_AWLEN(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWLEN),
    .I_AWSIZE(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWSIZE),
    .I_AWLOCK(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWLOCK),
    .I_AWCACHE(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWCACHE),
    .I_AWQOS(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWQOS),
    .I_AWPROT(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWPROT),
    .I_AWUSER(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWUSER),
    .I_AWBURST(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWBURST),
    .I_AWREGION(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWREGION),
    .I_WVALID(data_WVALID),
    .I_WREADY(data_WREADY),
    .I_WDATA(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WDATA),
    .I_WID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WID),
    .I_WUSER(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WUSER),
    .I_WLAST(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WLAST),
    .I_WSTRB(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WSTRB),
    .I_BVALID(data_BVALID),
    .I_BREADY(data_BREADY),
    .I_BRESP(data_BRESP),
    .I_BID(data_BID),
    .I_BUSER(data_BUSER)
);

conv_top_data1_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_DATA1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_DATA1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_DATA1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_DATA1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_DATA1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_DATA1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_DATA1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_DATA1_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_DATA1_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_DATA1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_DATA1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_DATA1_CACHE_VALUE ))
conv_top_data1_m_axi_U(
    .AWVALID(m_axi_data1_AWVALID),
    .AWREADY(m_axi_data1_AWREADY),
    .AWADDR(m_axi_data1_AWADDR),
    .AWID(m_axi_data1_AWID),
    .AWLEN(m_axi_data1_AWLEN),
    .AWSIZE(m_axi_data1_AWSIZE),
    .AWBURST(m_axi_data1_AWBURST),
    .AWLOCK(m_axi_data1_AWLOCK),
    .AWCACHE(m_axi_data1_AWCACHE),
    .AWPROT(m_axi_data1_AWPROT),
    .AWQOS(m_axi_data1_AWQOS),
    .AWREGION(m_axi_data1_AWREGION),
    .AWUSER(m_axi_data1_AWUSER),
    .WVALID(m_axi_data1_WVALID),
    .WREADY(m_axi_data1_WREADY),
    .WDATA(m_axi_data1_WDATA),
    .WSTRB(m_axi_data1_WSTRB),
    .WLAST(m_axi_data1_WLAST),
    .WID(m_axi_data1_WID),
    .WUSER(m_axi_data1_WUSER),
    .ARVALID(m_axi_data1_ARVALID),
    .ARREADY(m_axi_data1_ARREADY),
    .ARADDR(m_axi_data1_ARADDR),
    .ARID(m_axi_data1_ARID),
    .ARLEN(m_axi_data1_ARLEN),
    .ARSIZE(m_axi_data1_ARSIZE),
    .ARBURST(m_axi_data1_ARBURST),
    .ARLOCK(m_axi_data1_ARLOCK),
    .ARCACHE(m_axi_data1_ARCACHE),
    .ARPROT(m_axi_data1_ARPROT),
    .ARQOS(m_axi_data1_ARQOS),
    .ARREGION(m_axi_data1_ARREGION),
    .ARUSER(m_axi_data1_ARUSER),
    .RVALID(m_axi_data1_RVALID),
    .RREADY(m_axi_data1_RREADY),
    .RDATA(m_axi_data1_RDATA),
    .RLAST(m_axi_data1_RLAST),
    .RID(m_axi_data1_RID),
    .RUSER(m_axi_data1_RUSER),
    .RRESP(m_axi_data1_RRESP),
    .BVALID(m_axi_data1_BVALID),
    .BREADY(m_axi_data1_BREADY),
    .BRESP(m_axi_data1_BRESP),
    .BID(m_axi_data1_BID),
    .BUSER(m_axi_data1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(data1_ARVALID),
    .I_ARREADY(data1_ARREADY),
    .I_ARADDR(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARADDR),
    .I_ARID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARID),
    .I_ARLEN(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARLEN),
    .I_ARSIZE(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARSIZE),
    .I_ARLOCK(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARLOCK),
    .I_ARCACHE(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARCACHE),
    .I_ARQOS(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARQOS),
    .I_ARPROT(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARPROT),
    .I_ARUSER(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARUSER),
    .I_ARBURST(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARBURST),
    .I_ARREGION(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARREGION),
    .I_RVALID(data1_RVALID),
    .I_RREADY(data1_RREADY),
    .I_RDATA(data1_RDATA),
    .I_RID(data1_RID),
    .I_RUSER(data1_RUSER),
    .I_RRESP(data1_RRESP),
    .I_RLAST(data1_RLAST),
    .I_AWVALID(data1_AWVALID),
    .I_AWREADY(data1_AWREADY),
    .I_AWADDR(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWADDR),
    .I_AWID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWID),
    .I_AWLEN(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWLEN),
    .I_AWSIZE(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWSIZE),
    .I_AWLOCK(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWLOCK),
    .I_AWCACHE(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWCACHE),
    .I_AWQOS(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWQOS),
    .I_AWPROT(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWPROT),
    .I_AWUSER(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWUSER),
    .I_AWBURST(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWBURST),
    .I_AWREGION(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWREGION),
    .I_WVALID(data1_WVALID),
    .I_WREADY(data1_WREADY),
    .I_WDATA(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WDATA),
    .I_WID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WID),
    .I_WUSER(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WUSER),
    .I_WLAST(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WLAST),
    .I_WSTRB(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WSTRB),
    .I_BVALID(data1_BVALID),
    .I_BREADY(data1_BREADY),
    .I_BRESP(data1_BRESP),
    .I_BID(data1_BID),
    .I_BUSER(data1_BUSER)
);

conv_top_data2_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_DATA2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_DATA2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_DATA2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_DATA2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_DATA2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_DATA2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_DATA2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_DATA2_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_DATA2_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_DATA2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_DATA2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_DATA2_CACHE_VALUE ))
conv_top_data2_m_axi_U(
    .AWVALID(m_axi_data2_AWVALID),
    .AWREADY(m_axi_data2_AWREADY),
    .AWADDR(m_axi_data2_AWADDR),
    .AWID(m_axi_data2_AWID),
    .AWLEN(m_axi_data2_AWLEN),
    .AWSIZE(m_axi_data2_AWSIZE),
    .AWBURST(m_axi_data2_AWBURST),
    .AWLOCK(m_axi_data2_AWLOCK),
    .AWCACHE(m_axi_data2_AWCACHE),
    .AWPROT(m_axi_data2_AWPROT),
    .AWQOS(m_axi_data2_AWQOS),
    .AWREGION(m_axi_data2_AWREGION),
    .AWUSER(m_axi_data2_AWUSER),
    .WVALID(m_axi_data2_WVALID),
    .WREADY(m_axi_data2_WREADY),
    .WDATA(m_axi_data2_WDATA),
    .WSTRB(m_axi_data2_WSTRB),
    .WLAST(m_axi_data2_WLAST),
    .WID(m_axi_data2_WID),
    .WUSER(m_axi_data2_WUSER),
    .ARVALID(m_axi_data2_ARVALID),
    .ARREADY(m_axi_data2_ARREADY),
    .ARADDR(m_axi_data2_ARADDR),
    .ARID(m_axi_data2_ARID),
    .ARLEN(m_axi_data2_ARLEN),
    .ARSIZE(m_axi_data2_ARSIZE),
    .ARBURST(m_axi_data2_ARBURST),
    .ARLOCK(m_axi_data2_ARLOCK),
    .ARCACHE(m_axi_data2_ARCACHE),
    .ARPROT(m_axi_data2_ARPROT),
    .ARQOS(m_axi_data2_ARQOS),
    .ARREGION(m_axi_data2_ARREGION),
    .ARUSER(m_axi_data2_ARUSER),
    .RVALID(m_axi_data2_RVALID),
    .RREADY(m_axi_data2_RREADY),
    .RDATA(m_axi_data2_RDATA),
    .RLAST(m_axi_data2_RLAST),
    .RID(m_axi_data2_RID),
    .RUSER(m_axi_data2_RUSER),
    .RRESP(m_axi_data2_RRESP),
    .BVALID(m_axi_data2_BVALID),
    .BREADY(m_axi_data2_BREADY),
    .BRESP(m_axi_data2_BRESP),
    .BID(m_axi_data2_BID),
    .BUSER(m_axi_data2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(data2_ARVALID),
    .I_ARREADY(data2_ARREADY),
    .I_ARADDR(data2_ARADDR),
    .I_ARID(data2_ARID),
    .I_ARLEN(data2_ARLEN),
    .I_ARSIZE(data2_ARSIZE),
    .I_ARLOCK(data2_ARLOCK),
    .I_ARCACHE(data2_ARCACHE),
    .I_ARQOS(data2_ARQOS),
    .I_ARPROT(data2_ARPROT),
    .I_ARUSER(data2_ARUSER),
    .I_ARBURST(data2_ARBURST),
    .I_ARREGION(data2_ARREGION),
    .I_RVALID(data2_RVALID),
    .I_RREADY(data2_RREADY),
    .I_RDATA(data2_RDATA),
    .I_RID(data2_RID),
    .I_RUSER(data2_RUSER),
    .I_RRESP(data2_RRESP),
    .I_RLAST(data2_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(data2_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(data2_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(data2_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(data2_BRESP),
    .I_BID(data2_BID),
    .I_BUSER(data2_BUSER)
);

conv_top_data3_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_DATA3_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_DATA3_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_DATA3_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_DATA3_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_DATA3_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_DATA3_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_DATA3_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_DATA3_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_DATA3_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_DATA3_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_DATA3_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_DATA3_CACHE_VALUE ))
conv_top_data3_m_axi_U(
    .AWVALID(m_axi_data3_AWVALID),
    .AWREADY(m_axi_data3_AWREADY),
    .AWADDR(m_axi_data3_AWADDR),
    .AWID(m_axi_data3_AWID),
    .AWLEN(m_axi_data3_AWLEN),
    .AWSIZE(m_axi_data3_AWSIZE),
    .AWBURST(m_axi_data3_AWBURST),
    .AWLOCK(m_axi_data3_AWLOCK),
    .AWCACHE(m_axi_data3_AWCACHE),
    .AWPROT(m_axi_data3_AWPROT),
    .AWQOS(m_axi_data3_AWQOS),
    .AWREGION(m_axi_data3_AWREGION),
    .AWUSER(m_axi_data3_AWUSER),
    .WVALID(m_axi_data3_WVALID),
    .WREADY(m_axi_data3_WREADY),
    .WDATA(m_axi_data3_WDATA),
    .WSTRB(m_axi_data3_WSTRB),
    .WLAST(m_axi_data3_WLAST),
    .WID(m_axi_data3_WID),
    .WUSER(m_axi_data3_WUSER),
    .ARVALID(m_axi_data3_ARVALID),
    .ARREADY(m_axi_data3_ARREADY),
    .ARADDR(m_axi_data3_ARADDR),
    .ARID(m_axi_data3_ARID),
    .ARLEN(m_axi_data3_ARLEN),
    .ARSIZE(m_axi_data3_ARSIZE),
    .ARBURST(m_axi_data3_ARBURST),
    .ARLOCK(m_axi_data3_ARLOCK),
    .ARCACHE(m_axi_data3_ARCACHE),
    .ARPROT(m_axi_data3_ARPROT),
    .ARQOS(m_axi_data3_ARQOS),
    .ARREGION(m_axi_data3_ARREGION),
    .ARUSER(m_axi_data3_ARUSER),
    .RVALID(m_axi_data3_RVALID),
    .RREADY(m_axi_data3_RREADY),
    .RDATA(m_axi_data3_RDATA),
    .RLAST(m_axi_data3_RLAST),
    .RID(m_axi_data3_RID),
    .RUSER(m_axi_data3_RUSER),
    .RRESP(m_axi_data3_RRESP),
    .BVALID(m_axi_data3_BVALID),
    .BREADY(m_axi_data3_BREADY),
    .BRESP(m_axi_data3_BRESP),
    .BID(m_axi_data3_BID),
    .BUSER(m_axi_data3_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(data3_ARVALID),
    .I_ARREADY(data3_ARREADY),
    .I_ARADDR(data3_ARADDR),
    .I_ARID(data3_ARID),
    .I_ARLEN(data3_ARLEN),
    .I_ARSIZE(data3_ARSIZE),
    .I_ARLOCK(data3_ARLOCK),
    .I_ARCACHE(data3_ARCACHE),
    .I_ARQOS(data3_ARQOS),
    .I_ARPROT(data3_ARPROT),
    .I_ARUSER(data3_ARUSER),
    .I_ARBURST(data3_ARBURST),
    .I_ARREGION(data3_ARREGION),
    .I_RVALID(data3_RVALID),
    .I_RREADY(data3_RREADY),
    .I_RDATA(data3_RDATA),
    .I_RID(data3_RID),
    .I_RUSER(data3_RUSER),
    .I_RRESP(data3_RRESP),
    .I_RLAST(data3_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(data3_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(data3_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(data3_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(data3_BRESP),
    .I_BID(data3_BID),
    .I_BUSER(data3_BUSER)
);

conv1 grp_conv1_fu_50(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_conv1_fu_50_ap_start),
    .ap_done(grp_conv1_fu_50_ap_done),
    .ap_idle(grp_conv1_fu_50_ap_idle),
    .ap_ready(grp_conv1_fu_50_ap_ready),
    .m_axi_FM_DDR_BUFF1_AWVALID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWVALID),
    .m_axi_FM_DDR_BUFF1_AWREADY(1'b0),
    .m_axi_FM_DDR_BUFF1_AWADDR(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWADDR),
    .m_axi_FM_DDR_BUFF1_AWID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWID),
    .m_axi_FM_DDR_BUFF1_AWLEN(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWLEN),
    .m_axi_FM_DDR_BUFF1_AWSIZE(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWSIZE),
    .m_axi_FM_DDR_BUFF1_AWBURST(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWBURST),
    .m_axi_FM_DDR_BUFF1_AWLOCK(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWLOCK),
    .m_axi_FM_DDR_BUFF1_AWCACHE(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWCACHE),
    .m_axi_FM_DDR_BUFF1_AWPROT(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWPROT),
    .m_axi_FM_DDR_BUFF1_AWQOS(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWQOS),
    .m_axi_FM_DDR_BUFF1_AWREGION(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWREGION),
    .m_axi_FM_DDR_BUFF1_AWUSER(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_AWUSER),
    .m_axi_FM_DDR_BUFF1_WVALID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_WVALID),
    .m_axi_FM_DDR_BUFF1_WREADY(1'b0),
    .m_axi_FM_DDR_BUFF1_WDATA(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_WDATA),
    .m_axi_FM_DDR_BUFF1_WSTRB(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_WSTRB),
    .m_axi_FM_DDR_BUFF1_WLAST(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_WLAST),
    .m_axi_FM_DDR_BUFF1_WID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_WID),
    .m_axi_FM_DDR_BUFF1_WUSER(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_WUSER),
    .m_axi_FM_DDR_BUFF1_ARVALID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARVALID),
    .m_axi_FM_DDR_BUFF1_ARREADY(data_ARREADY),
    .m_axi_FM_DDR_BUFF1_ARADDR(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARADDR),
    .m_axi_FM_DDR_BUFF1_ARID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARID),
    .m_axi_FM_DDR_BUFF1_ARLEN(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARLEN),
    .m_axi_FM_DDR_BUFF1_ARSIZE(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARSIZE),
    .m_axi_FM_DDR_BUFF1_ARBURST(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARBURST),
    .m_axi_FM_DDR_BUFF1_ARLOCK(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARLOCK),
    .m_axi_FM_DDR_BUFF1_ARCACHE(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARCACHE),
    .m_axi_FM_DDR_BUFF1_ARPROT(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARPROT),
    .m_axi_FM_DDR_BUFF1_ARQOS(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARQOS),
    .m_axi_FM_DDR_BUFF1_ARREGION(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARREGION),
    .m_axi_FM_DDR_BUFF1_ARUSER(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARUSER),
    .m_axi_FM_DDR_BUFF1_RVALID(data_RVALID),
    .m_axi_FM_DDR_BUFF1_RREADY(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_RREADY),
    .m_axi_FM_DDR_BUFF1_RDATA(data_RDATA),
    .m_axi_FM_DDR_BUFF1_RLAST(data_RLAST),
    .m_axi_FM_DDR_BUFF1_RID(data_RID),
    .m_axi_FM_DDR_BUFF1_RUSER(data_RUSER),
    .m_axi_FM_DDR_BUFF1_RRESP(data_RRESP),
    .m_axi_FM_DDR_BUFF1_BVALID(1'b0),
    .m_axi_FM_DDR_BUFF1_BREADY(grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_BREADY),
    .m_axi_FM_DDR_BUFF1_BRESP(2'd0),
    .m_axi_FM_DDR_BUFF1_BID(1'd0),
    .m_axi_FM_DDR_BUFF1_BUSER(1'd0),
    .m_axi_FM_DDR_BUFF2_AWVALID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWVALID),
    .m_axi_FM_DDR_BUFF2_AWREADY(data1_AWREADY),
    .m_axi_FM_DDR_BUFF2_AWADDR(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWADDR),
    .m_axi_FM_DDR_BUFF2_AWID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWID),
    .m_axi_FM_DDR_BUFF2_AWLEN(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWLEN),
    .m_axi_FM_DDR_BUFF2_AWSIZE(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWSIZE),
    .m_axi_FM_DDR_BUFF2_AWBURST(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWBURST),
    .m_axi_FM_DDR_BUFF2_AWLOCK(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWLOCK),
    .m_axi_FM_DDR_BUFF2_AWCACHE(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWCACHE),
    .m_axi_FM_DDR_BUFF2_AWPROT(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWPROT),
    .m_axi_FM_DDR_BUFF2_AWQOS(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWQOS),
    .m_axi_FM_DDR_BUFF2_AWREGION(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWREGION),
    .m_axi_FM_DDR_BUFF2_AWUSER(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWUSER),
    .m_axi_FM_DDR_BUFF2_WVALID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WVALID),
    .m_axi_FM_DDR_BUFF2_WREADY(data1_WREADY),
    .m_axi_FM_DDR_BUFF2_WDATA(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WDATA),
    .m_axi_FM_DDR_BUFF2_WSTRB(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WSTRB),
    .m_axi_FM_DDR_BUFF2_WLAST(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WLAST),
    .m_axi_FM_DDR_BUFF2_WID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WID),
    .m_axi_FM_DDR_BUFF2_WUSER(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WUSER),
    .m_axi_FM_DDR_BUFF2_ARVALID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARVALID),
    .m_axi_FM_DDR_BUFF2_ARREADY(1'b0),
    .m_axi_FM_DDR_BUFF2_ARADDR(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARADDR),
    .m_axi_FM_DDR_BUFF2_ARID(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARID),
    .m_axi_FM_DDR_BUFF2_ARLEN(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARLEN),
    .m_axi_FM_DDR_BUFF2_ARSIZE(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARSIZE),
    .m_axi_FM_DDR_BUFF2_ARBURST(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARBURST),
    .m_axi_FM_DDR_BUFF2_ARLOCK(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARLOCK),
    .m_axi_FM_DDR_BUFF2_ARCACHE(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARCACHE),
    .m_axi_FM_DDR_BUFF2_ARPROT(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARPROT),
    .m_axi_FM_DDR_BUFF2_ARQOS(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARQOS),
    .m_axi_FM_DDR_BUFF2_ARREGION(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARREGION),
    .m_axi_FM_DDR_BUFF2_ARUSER(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_ARUSER),
    .m_axi_FM_DDR_BUFF2_RVALID(1'b0),
    .m_axi_FM_DDR_BUFF2_RREADY(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_RREADY),
    .m_axi_FM_DDR_BUFF2_RDATA(32'd0),
    .m_axi_FM_DDR_BUFF2_RLAST(1'b0),
    .m_axi_FM_DDR_BUFF2_RID(1'd0),
    .m_axi_FM_DDR_BUFF2_RUSER(1'd0),
    .m_axi_FM_DDR_BUFF2_RRESP(2'd0),
    .m_axi_FM_DDR_BUFF2_BVALID(data1_BVALID),
    .m_axi_FM_DDR_BUFF2_BREADY(grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_BREADY),
    .m_axi_FM_DDR_BUFF2_BRESP(data1_BRESP),
    .m_axi_FM_DDR_BUFF2_BID(data1_BID),
    .m_axi_FM_DDR_BUFF2_BUSER(data1_BUSER),
    .m_axi_WEIGHT_AWVALID(grp_conv1_fu_50_m_axi_WEIGHT_AWVALID),
    .m_axi_WEIGHT_AWREADY(1'b0),
    .m_axi_WEIGHT_AWADDR(grp_conv1_fu_50_m_axi_WEIGHT_AWADDR),
    .m_axi_WEIGHT_AWID(grp_conv1_fu_50_m_axi_WEIGHT_AWID),
    .m_axi_WEIGHT_AWLEN(grp_conv1_fu_50_m_axi_WEIGHT_AWLEN),
    .m_axi_WEIGHT_AWSIZE(grp_conv1_fu_50_m_axi_WEIGHT_AWSIZE),
    .m_axi_WEIGHT_AWBURST(grp_conv1_fu_50_m_axi_WEIGHT_AWBURST),
    .m_axi_WEIGHT_AWLOCK(grp_conv1_fu_50_m_axi_WEIGHT_AWLOCK),
    .m_axi_WEIGHT_AWCACHE(grp_conv1_fu_50_m_axi_WEIGHT_AWCACHE),
    .m_axi_WEIGHT_AWPROT(grp_conv1_fu_50_m_axi_WEIGHT_AWPROT),
    .m_axi_WEIGHT_AWQOS(grp_conv1_fu_50_m_axi_WEIGHT_AWQOS),
    .m_axi_WEIGHT_AWREGION(grp_conv1_fu_50_m_axi_WEIGHT_AWREGION),
    .m_axi_WEIGHT_AWUSER(grp_conv1_fu_50_m_axi_WEIGHT_AWUSER),
    .m_axi_WEIGHT_WVALID(grp_conv1_fu_50_m_axi_WEIGHT_WVALID),
    .m_axi_WEIGHT_WREADY(1'b0),
    .m_axi_WEIGHT_WDATA(grp_conv1_fu_50_m_axi_WEIGHT_WDATA),
    .m_axi_WEIGHT_WSTRB(grp_conv1_fu_50_m_axi_WEIGHT_WSTRB),
    .m_axi_WEIGHT_WLAST(grp_conv1_fu_50_m_axi_WEIGHT_WLAST),
    .m_axi_WEIGHT_WID(grp_conv1_fu_50_m_axi_WEIGHT_WID),
    .m_axi_WEIGHT_WUSER(grp_conv1_fu_50_m_axi_WEIGHT_WUSER),
    .m_axi_WEIGHT_ARVALID(grp_conv1_fu_50_m_axi_WEIGHT_ARVALID),
    .m_axi_WEIGHT_ARREADY(data2_ARREADY),
    .m_axi_WEIGHT_ARADDR(grp_conv1_fu_50_m_axi_WEIGHT_ARADDR),
    .m_axi_WEIGHT_ARID(grp_conv1_fu_50_m_axi_WEIGHT_ARID),
    .m_axi_WEIGHT_ARLEN(grp_conv1_fu_50_m_axi_WEIGHT_ARLEN),
    .m_axi_WEIGHT_ARSIZE(grp_conv1_fu_50_m_axi_WEIGHT_ARSIZE),
    .m_axi_WEIGHT_ARBURST(grp_conv1_fu_50_m_axi_WEIGHT_ARBURST),
    .m_axi_WEIGHT_ARLOCK(grp_conv1_fu_50_m_axi_WEIGHT_ARLOCK),
    .m_axi_WEIGHT_ARCACHE(grp_conv1_fu_50_m_axi_WEIGHT_ARCACHE),
    .m_axi_WEIGHT_ARPROT(grp_conv1_fu_50_m_axi_WEIGHT_ARPROT),
    .m_axi_WEIGHT_ARQOS(grp_conv1_fu_50_m_axi_WEIGHT_ARQOS),
    .m_axi_WEIGHT_ARREGION(grp_conv1_fu_50_m_axi_WEIGHT_ARREGION),
    .m_axi_WEIGHT_ARUSER(grp_conv1_fu_50_m_axi_WEIGHT_ARUSER),
    .m_axi_WEIGHT_RVALID(data2_RVALID),
    .m_axi_WEIGHT_RREADY(grp_conv1_fu_50_m_axi_WEIGHT_RREADY),
    .m_axi_WEIGHT_RDATA(data2_RDATA),
    .m_axi_WEIGHT_RLAST(data2_RLAST),
    .m_axi_WEIGHT_RID(data2_RID),
    .m_axi_WEIGHT_RUSER(data2_RUSER),
    .m_axi_WEIGHT_RRESP(data2_RRESP),
    .m_axi_WEIGHT_BVALID(1'b0),
    .m_axi_WEIGHT_BREADY(grp_conv1_fu_50_m_axi_WEIGHT_BREADY),
    .m_axi_WEIGHT_BRESP(2'd0),
    .m_axi_WEIGHT_BID(1'd0),
    .m_axi_WEIGHT_BUSER(1'd0),
    .m_axi_BIAS_AWVALID(grp_conv1_fu_50_m_axi_BIAS_AWVALID),
    .m_axi_BIAS_AWREADY(1'b0),
    .m_axi_BIAS_AWADDR(grp_conv1_fu_50_m_axi_BIAS_AWADDR),
    .m_axi_BIAS_AWID(grp_conv1_fu_50_m_axi_BIAS_AWID),
    .m_axi_BIAS_AWLEN(grp_conv1_fu_50_m_axi_BIAS_AWLEN),
    .m_axi_BIAS_AWSIZE(grp_conv1_fu_50_m_axi_BIAS_AWSIZE),
    .m_axi_BIAS_AWBURST(grp_conv1_fu_50_m_axi_BIAS_AWBURST),
    .m_axi_BIAS_AWLOCK(grp_conv1_fu_50_m_axi_BIAS_AWLOCK),
    .m_axi_BIAS_AWCACHE(grp_conv1_fu_50_m_axi_BIAS_AWCACHE),
    .m_axi_BIAS_AWPROT(grp_conv1_fu_50_m_axi_BIAS_AWPROT),
    .m_axi_BIAS_AWQOS(grp_conv1_fu_50_m_axi_BIAS_AWQOS),
    .m_axi_BIAS_AWREGION(grp_conv1_fu_50_m_axi_BIAS_AWREGION),
    .m_axi_BIAS_AWUSER(grp_conv1_fu_50_m_axi_BIAS_AWUSER),
    .m_axi_BIAS_WVALID(grp_conv1_fu_50_m_axi_BIAS_WVALID),
    .m_axi_BIAS_WREADY(1'b0),
    .m_axi_BIAS_WDATA(grp_conv1_fu_50_m_axi_BIAS_WDATA),
    .m_axi_BIAS_WSTRB(grp_conv1_fu_50_m_axi_BIAS_WSTRB),
    .m_axi_BIAS_WLAST(grp_conv1_fu_50_m_axi_BIAS_WLAST),
    .m_axi_BIAS_WID(grp_conv1_fu_50_m_axi_BIAS_WID),
    .m_axi_BIAS_WUSER(grp_conv1_fu_50_m_axi_BIAS_WUSER),
    .m_axi_BIAS_ARVALID(grp_conv1_fu_50_m_axi_BIAS_ARVALID),
    .m_axi_BIAS_ARREADY(data3_ARREADY),
    .m_axi_BIAS_ARADDR(grp_conv1_fu_50_m_axi_BIAS_ARADDR),
    .m_axi_BIAS_ARID(grp_conv1_fu_50_m_axi_BIAS_ARID),
    .m_axi_BIAS_ARLEN(grp_conv1_fu_50_m_axi_BIAS_ARLEN),
    .m_axi_BIAS_ARSIZE(grp_conv1_fu_50_m_axi_BIAS_ARSIZE),
    .m_axi_BIAS_ARBURST(grp_conv1_fu_50_m_axi_BIAS_ARBURST),
    .m_axi_BIAS_ARLOCK(grp_conv1_fu_50_m_axi_BIAS_ARLOCK),
    .m_axi_BIAS_ARCACHE(grp_conv1_fu_50_m_axi_BIAS_ARCACHE),
    .m_axi_BIAS_ARPROT(grp_conv1_fu_50_m_axi_BIAS_ARPROT),
    .m_axi_BIAS_ARQOS(grp_conv1_fu_50_m_axi_BIAS_ARQOS),
    .m_axi_BIAS_ARREGION(grp_conv1_fu_50_m_axi_BIAS_ARREGION),
    .m_axi_BIAS_ARUSER(grp_conv1_fu_50_m_axi_BIAS_ARUSER),
    .m_axi_BIAS_RVALID(data3_RVALID),
    .m_axi_BIAS_RREADY(grp_conv1_fu_50_m_axi_BIAS_RREADY),
    .m_axi_BIAS_RDATA(data3_RDATA),
    .m_axi_BIAS_RLAST(data3_RLAST),
    .m_axi_BIAS_RID(data3_RID),
    .m_axi_BIAS_RUSER(data3_RUSER),
    .m_axi_BIAS_RRESP(data3_RRESP),
    .m_axi_BIAS_BVALID(1'b0),
    .m_axi_BIAS_BREADY(grp_conv1_fu_50_m_axi_BIAS_BREADY),
    .m_axi_BIAS_BRESP(2'd0),
    .m_axi_BIAS_BID(1'd0),
    .m_axi_BIAS_BUSER(1'd0),
    .conv_out1_address0(grp_conv1_fu_50_conv_out1_address0),
    .conv_out1_ce0(grp_conv1_fu_50_conv_out1_ce0),
    .conv_out1_we0(grp_conv1_fu_50_conv_out1_we0),
    .conv_out1_d0(grp_conv1_fu_50_conv_out1_d0),
    .conv_out1_q0(conv_out1_q0)
);

conv2 grp_conv2_fu_72(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_conv2_fu_72_ap_start),
    .ap_done(grp_conv2_fu_72_ap_done),
    .ap_idle(grp_conv2_fu_72_ap_idle),
    .ap_ready(grp_conv2_fu_72_ap_ready),
    .m_axi_FM_DDR_BUFF1_AWVALID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWVALID),
    .m_axi_FM_DDR_BUFF1_AWREADY(data_AWREADY),
    .m_axi_FM_DDR_BUFF1_AWADDR(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWADDR),
    .m_axi_FM_DDR_BUFF1_AWID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWID),
    .m_axi_FM_DDR_BUFF1_AWLEN(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWLEN),
    .m_axi_FM_DDR_BUFF1_AWSIZE(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWSIZE),
    .m_axi_FM_DDR_BUFF1_AWBURST(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWBURST),
    .m_axi_FM_DDR_BUFF1_AWLOCK(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWLOCK),
    .m_axi_FM_DDR_BUFF1_AWCACHE(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWCACHE),
    .m_axi_FM_DDR_BUFF1_AWPROT(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWPROT),
    .m_axi_FM_DDR_BUFF1_AWQOS(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWQOS),
    .m_axi_FM_DDR_BUFF1_AWREGION(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWREGION),
    .m_axi_FM_DDR_BUFF1_AWUSER(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWUSER),
    .m_axi_FM_DDR_BUFF1_WVALID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WVALID),
    .m_axi_FM_DDR_BUFF1_WREADY(data_WREADY),
    .m_axi_FM_DDR_BUFF1_WDATA(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WDATA),
    .m_axi_FM_DDR_BUFF1_WSTRB(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WSTRB),
    .m_axi_FM_DDR_BUFF1_WLAST(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WLAST),
    .m_axi_FM_DDR_BUFF1_WID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WID),
    .m_axi_FM_DDR_BUFF1_WUSER(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WUSER),
    .m_axi_FM_DDR_BUFF1_ARVALID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARVALID),
    .m_axi_FM_DDR_BUFF1_ARREADY(1'b0),
    .m_axi_FM_DDR_BUFF1_ARADDR(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARADDR),
    .m_axi_FM_DDR_BUFF1_ARID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARID),
    .m_axi_FM_DDR_BUFF1_ARLEN(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARLEN),
    .m_axi_FM_DDR_BUFF1_ARSIZE(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARSIZE),
    .m_axi_FM_DDR_BUFF1_ARBURST(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARBURST),
    .m_axi_FM_DDR_BUFF1_ARLOCK(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARLOCK),
    .m_axi_FM_DDR_BUFF1_ARCACHE(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARCACHE),
    .m_axi_FM_DDR_BUFF1_ARPROT(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARPROT),
    .m_axi_FM_DDR_BUFF1_ARQOS(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARQOS),
    .m_axi_FM_DDR_BUFF1_ARREGION(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARREGION),
    .m_axi_FM_DDR_BUFF1_ARUSER(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_ARUSER),
    .m_axi_FM_DDR_BUFF1_RVALID(1'b0),
    .m_axi_FM_DDR_BUFF1_RREADY(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_RREADY),
    .m_axi_FM_DDR_BUFF1_RDATA(32'd0),
    .m_axi_FM_DDR_BUFF1_RLAST(1'b0),
    .m_axi_FM_DDR_BUFF1_RID(1'd0),
    .m_axi_FM_DDR_BUFF1_RUSER(1'd0),
    .m_axi_FM_DDR_BUFF1_RRESP(2'd0),
    .m_axi_FM_DDR_BUFF1_BVALID(data_BVALID),
    .m_axi_FM_DDR_BUFF1_BREADY(grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_BREADY),
    .m_axi_FM_DDR_BUFF1_BRESP(data_BRESP),
    .m_axi_FM_DDR_BUFF1_BID(data_BID),
    .m_axi_FM_DDR_BUFF1_BUSER(data_BUSER),
    .m_axi_FM_DDR_BUFF2_AWVALID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWVALID),
    .m_axi_FM_DDR_BUFF2_AWREADY(1'b0),
    .m_axi_FM_DDR_BUFF2_AWADDR(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWADDR),
    .m_axi_FM_DDR_BUFF2_AWID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWID),
    .m_axi_FM_DDR_BUFF2_AWLEN(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWLEN),
    .m_axi_FM_DDR_BUFF2_AWSIZE(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWSIZE),
    .m_axi_FM_DDR_BUFF2_AWBURST(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWBURST),
    .m_axi_FM_DDR_BUFF2_AWLOCK(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWLOCK),
    .m_axi_FM_DDR_BUFF2_AWCACHE(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWCACHE),
    .m_axi_FM_DDR_BUFF2_AWPROT(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWPROT),
    .m_axi_FM_DDR_BUFF2_AWQOS(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWQOS),
    .m_axi_FM_DDR_BUFF2_AWREGION(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWREGION),
    .m_axi_FM_DDR_BUFF2_AWUSER(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_AWUSER),
    .m_axi_FM_DDR_BUFF2_WVALID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_WVALID),
    .m_axi_FM_DDR_BUFF2_WREADY(1'b0),
    .m_axi_FM_DDR_BUFF2_WDATA(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_WDATA),
    .m_axi_FM_DDR_BUFF2_WSTRB(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_WSTRB),
    .m_axi_FM_DDR_BUFF2_WLAST(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_WLAST),
    .m_axi_FM_DDR_BUFF2_WID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_WID),
    .m_axi_FM_DDR_BUFF2_WUSER(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_WUSER),
    .m_axi_FM_DDR_BUFF2_ARVALID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARVALID),
    .m_axi_FM_DDR_BUFF2_ARREADY(data1_ARREADY),
    .m_axi_FM_DDR_BUFF2_ARADDR(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARADDR),
    .m_axi_FM_DDR_BUFF2_ARID(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARID),
    .m_axi_FM_DDR_BUFF2_ARLEN(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARLEN),
    .m_axi_FM_DDR_BUFF2_ARSIZE(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARSIZE),
    .m_axi_FM_DDR_BUFF2_ARBURST(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARBURST),
    .m_axi_FM_DDR_BUFF2_ARLOCK(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARLOCK),
    .m_axi_FM_DDR_BUFF2_ARCACHE(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARCACHE),
    .m_axi_FM_DDR_BUFF2_ARPROT(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARPROT),
    .m_axi_FM_DDR_BUFF2_ARQOS(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARQOS),
    .m_axi_FM_DDR_BUFF2_ARREGION(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARREGION),
    .m_axi_FM_DDR_BUFF2_ARUSER(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARUSER),
    .m_axi_FM_DDR_BUFF2_RVALID(data1_RVALID),
    .m_axi_FM_DDR_BUFF2_RREADY(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_RREADY),
    .m_axi_FM_DDR_BUFF2_RDATA(data1_RDATA),
    .m_axi_FM_DDR_BUFF2_RLAST(data1_RLAST),
    .m_axi_FM_DDR_BUFF2_RID(data1_RID),
    .m_axi_FM_DDR_BUFF2_RUSER(data1_RUSER),
    .m_axi_FM_DDR_BUFF2_RRESP(data1_RRESP),
    .m_axi_FM_DDR_BUFF2_BVALID(1'b0),
    .m_axi_FM_DDR_BUFF2_BREADY(grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_BREADY),
    .m_axi_FM_DDR_BUFF2_BRESP(2'd0),
    .m_axi_FM_DDR_BUFF2_BID(1'd0),
    .m_axi_FM_DDR_BUFF2_BUSER(1'd0),
    .m_axi_WEIGHT_AWVALID(grp_conv2_fu_72_m_axi_WEIGHT_AWVALID),
    .m_axi_WEIGHT_AWREADY(1'b0),
    .m_axi_WEIGHT_AWADDR(grp_conv2_fu_72_m_axi_WEIGHT_AWADDR),
    .m_axi_WEIGHT_AWID(grp_conv2_fu_72_m_axi_WEIGHT_AWID),
    .m_axi_WEIGHT_AWLEN(grp_conv2_fu_72_m_axi_WEIGHT_AWLEN),
    .m_axi_WEIGHT_AWSIZE(grp_conv2_fu_72_m_axi_WEIGHT_AWSIZE),
    .m_axi_WEIGHT_AWBURST(grp_conv2_fu_72_m_axi_WEIGHT_AWBURST),
    .m_axi_WEIGHT_AWLOCK(grp_conv2_fu_72_m_axi_WEIGHT_AWLOCK),
    .m_axi_WEIGHT_AWCACHE(grp_conv2_fu_72_m_axi_WEIGHT_AWCACHE),
    .m_axi_WEIGHT_AWPROT(grp_conv2_fu_72_m_axi_WEIGHT_AWPROT),
    .m_axi_WEIGHT_AWQOS(grp_conv2_fu_72_m_axi_WEIGHT_AWQOS),
    .m_axi_WEIGHT_AWREGION(grp_conv2_fu_72_m_axi_WEIGHT_AWREGION),
    .m_axi_WEIGHT_AWUSER(grp_conv2_fu_72_m_axi_WEIGHT_AWUSER),
    .m_axi_WEIGHT_WVALID(grp_conv2_fu_72_m_axi_WEIGHT_WVALID),
    .m_axi_WEIGHT_WREADY(1'b0),
    .m_axi_WEIGHT_WDATA(grp_conv2_fu_72_m_axi_WEIGHT_WDATA),
    .m_axi_WEIGHT_WSTRB(grp_conv2_fu_72_m_axi_WEIGHT_WSTRB),
    .m_axi_WEIGHT_WLAST(grp_conv2_fu_72_m_axi_WEIGHT_WLAST),
    .m_axi_WEIGHT_WID(grp_conv2_fu_72_m_axi_WEIGHT_WID),
    .m_axi_WEIGHT_WUSER(grp_conv2_fu_72_m_axi_WEIGHT_WUSER),
    .m_axi_WEIGHT_ARVALID(grp_conv2_fu_72_m_axi_WEIGHT_ARVALID),
    .m_axi_WEIGHT_ARREADY(data2_ARREADY),
    .m_axi_WEIGHT_ARADDR(grp_conv2_fu_72_m_axi_WEIGHT_ARADDR),
    .m_axi_WEIGHT_ARID(grp_conv2_fu_72_m_axi_WEIGHT_ARID),
    .m_axi_WEIGHT_ARLEN(grp_conv2_fu_72_m_axi_WEIGHT_ARLEN),
    .m_axi_WEIGHT_ARSIZE(grp_conv2_fu_72_m_axi_WEIGHT_ARSIZE),
    .m_axi_WEIGHT_ARBURST(grp_conv2_fu_72_m_axi_WEIGHT_ARBURST),
    .m_axi_WEIGHT_ARLOCK(grp_conv2_fu_72_m_axi_WEIGHT_ARLOCK),
    .m_axi_WEIGHT_ARCACHE(grp_conv2_fu_72_m_axi_WEIGHT_ARCACHE),
    .m_axi_WEIGHT_ARPROT(grp_conv2_fu_72_m_axi_WEIGHT_ARPROT),
    .m_axi_WEIGHT_ARQOS(grp_conv2_fu_72_m_axi_WEIGHT_ARQOS),
    .m_axi_WEIGHT_ARREGION(grp_conv2_fu_72_m_axi_WEIGHT_ARREGION),
    .m_axi_WEIGHT_ARUSER(grp_conv2_fu_72_m_axi_WEIGHT_ARUSER),
    .m_axi_WEIGHT_RVALID(data2_RVALID),
    .m_axi_WEIGHT_RREADY(grp_conv2_fu_72_m_axi_WEIGHT_RREADY),
    .m_axi_WEIGHT_RDATA(data2_RDATA),
    .m_axi_WEIGHT_RLAST(data2_RLAST),
    .m_axi_WEIGHT_RID(data2_RID),
    .m_axi_WEIGHT_RUSER(data2_RUSER),
    .m_axi_WEIGHT_RRESP(data2_RRESP),
    .m_axi_WEIGHT_BVALID(1'b0),
    .m_axi_WEIGHT_BREADY(grp_conv2_fu_72_m_axi_WEIGHT_BREADY),
    .m_axi_WEIGHT_BRESP(2'd0),
    .m_axi_WEIGHT_BID(1'd0),
    .m_axi_WEIGHT_BUSER(1'd0),
    .m_axi_BIAS_AWVALID(grp_conv2_fu_72_m_axi_BIAS_AWVALID),
    .m_axi_BIAS_AWREADY(1'b0),
    .m_axi_BIAS_AWADDR(grp_conv2_fu_72_m_axi_BIAS_AWADDR),
    .m_axi_BIAS_AWID(grp_conv2_fu_72_m_axi_BIAS_AWID),
    .m_axi_BIAS_AWLEN(grp_conv2_fu_72_m_axi_BIAS_AWLEN),
    .m_axi_BIAS_AWSIZE(grp_conv2_fu_72_m_axi_BIAS_AWSIZE),
    .m_axi_BIAS_AWBURST(grp_conv2_fu_72_m_axi_BIAS_AWBURST),
    .m_axi_BIAS_AWLOCK(grp_conv2_fu_72_m_axi_BIAS_AWLOCK),
    .m_axi_BIAS_AWCACHE(grp_conv2_fu_72_m_axi_BIAS_AWCACHE),
    .m_axi_BIAS_AWPROT(grp_conv2_fu_72_m_axi_BIAS_AWPROT),
    .m_axi_BIAS_AWQOS(grp_conv2_fu_72_m_axi_BIAS_AWQOS),
    .m_axi_BIAS_AWREGION(grp_conv2_fu_72_m_axi_BIAS_AWREGION),
    .m_axi_BIAS_AWUSER(grp_conv2_fu_72_m_axi_BIAS_AWUSER),
    .m_axi_BIAS_WVALID(grp_conv2_fu_72_m_axi_BIAS_WVALID),
    .m_axi_BIAS_WREADY(1'b0),
    .m_axi_BIAS_WDATA(grp_conv2_fu_72_m_axi_BIAS_WDATA),
    .m_axi_BIAS_WSTRB(grp_conv2_fu_72_m_axi_BIAS_WSTRB),
    .m_axi_BIAS_WLAST(grp_conv2_fu_72_m_axi_BIAS_WLAST),
    .m_axi_BIAS_WID(grp_conv2_fu_72_m_axi_BIAS_WID),
    .m_axi_BIAS_WUSER(grp_conv2_fu_72_m_axi_BIAS_WUSER),
    .m_axi_BIAS_ARVALID(grp_conv2_fu_72_m_axi_BIAS_ARVALID),
    .m_axi_BIAS_ARREADY(data3_ARREADY),
    .m_axi_BIAS_ARADDR(grp_conv2_fu_72_m_axi_BIAS_ARADDR),
    .m_axi_BIAS_ARID(grp_conv2_fu_72_m_axi_BIAS_ARID),
    .m_axi_BIAS_ARLEN(grp_conv2_fu_72_m_axi_BIAS_ARLEN),
    .m_axi_BIAS_ARSIZE(grp_conv2_fu_72_m_axi_BIAS_ARSIZE),
    .m_axi_BIAS_ARBURST(grp_conv2_fu_72_m_axi_BIAS_ARBURST),
    .m_axi_BIAS_ARLOCK(grp_conv2_fu_72_m_axi_BIAS_ARLOCK),
    .m_axi_BIAS_ARCACHE(grp_conv2_fu_72_m_axi_BIAS_ARCACHE),
    .m_axi_BIAS_ARPROT(grp_conv2_fu_72_m_axi_BIAS_ARPROT),
    .m_axi_BIAS_ARQOS(grp_conv2_fu_72_m_axi_BIAS_ARQOS),
    .m_axi_BIAS_ARREGION(grp_conv2_fu_72_m_axi_BIAS_ARREGION),
    .m_axi_BIAS_ARUSER(grp_conv2_fu_72_m_axi_BIAS_ARUSER),
    .m_axi_BIAS_RVALID(data3_RVALID),
    .m_axi_BIAS_RREADY(grp_conv2_fu_72_m_axi_BIAS_RREADY),
    .m_axi_BIAS_RDATA(data3_RDATA),
    .m_axi_BIAS_RLAST(data3_RLAST),
    .m_axi_BIAS_RID(data3_RID),
    .m_axi_BIAS_RUSER(data3_RUSER),
    .m_axi_BIAS_RRESP(data3_RRESP),
    .m_axi_BIAS_BVALID(1'b0),
    .m_axi_BIAS_BREADY(grp_conv2_fu_72_m_axi_BIAS_BREADY),
    .m_axi_BIAS_BRESP(2'd0),
    .m_axi_BIAS_BID(1'd0),
    .m_axi_BIAS_BUSER(1'd0),
    .conv_out1_address0(grp_conv2_fu_72_conv_out1_address0),
    .conv_out1_ce0(grp_conv2_fu_72_conv_out1_ce0),
    .conv_out1_we0(grp_conv2_fu_72_conv_out1_we0),
    .conv_out1_d0(grp_conv2_fu_72_conv_out1_d0),
    .conv_out1_q0(conv_out1_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_conv1_fu_50_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_conv1_fu_50_ap_start_reg <= 1'b1;
        end else if ((grp_conv1_fu_50_ap_ready == 1'b1)) begin
            grp_conv1_fu_50_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_conv2_fu_72_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_conv2_fu_72_ap_start_reg <= 1'b1;
        end else if ((grp_conv2_fu_72_ap_ready == 1'b1)) begin
            grp_conv2_fu_72_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((grp_conv2_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_conv2_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        conv_out1_address0 = grp_conv2_fu_72_conv_out1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        conv_out1_address0 = grp_conv1_fu_50_conv_out1_address0;
    end else begin
        conv_out1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        conv_out1_ce0 = grp_conv2_fu_72_conv_out1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        conv_out1_ce0 = grp_conv1_fu_50_conv_out1_ce0;
    end else begin
        conv_out1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        conv_out1_d0 = grp_conv2_fu_72_conv_out1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        conv_out1_d0 = grp_conv1_fu_50_conv_out1_d0;
    end else begin
        conv_out1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        conv_out1_we0 = grp_conv2_fu_72_conv_out1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        conv_out1_we0 = grp_conv1_fu_50_conv_out1_we0;
    end else begin
        conv_out1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data1_ARVALID = grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_ARVALID;
    end else begin
        data1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data1_AWVALID = grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_AWVALID;
    end else begin
        data1_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data1_BREADY = grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_BREADY;
    end else begin
        data1_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data1_RREADY = grp_conv2_fu_72_m_axi_FM_DDR_BUFF2_RREADY;
    end else begin
        data1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data1_WVALID = grp_conv1_fu_50_m_axi_FM_DDR_BUFF2_WVALID;
    end else begin
        data1_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data2_ARADDR = grp_conv2_fu_72_m_axi_WEIGHT_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data2_ARADDR = grp_conv1_fu_50_m_axi_WEIGHT_ARADDR;
    end else begin
        data2_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data2_ARBURST = grp_conv2_fu_72_m_axi_WEIGHT_ARBURST;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data2_ARBURST = grp_conv1_fu_50_m_axi_WEIGHT_ARBURST;
    end else begin
        data2_ARBURST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data2_ARCACHE = grp_conv2_fu_72_m_axi_WEIGHT_ARCACHE;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data2_ARCACHE = grp_conv1_fu_50_m_axi_WEIGHT_ARCACHE;
    end else begin
        data2_ARCACHE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data2_ARID = grp_conv2_fu_72_m_axi_WEIGHT_ARID;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data2_ARID = grp_conv1_fu_50_m_axi_WEIGHT_ARID;
    end else begin
        data2_ARID = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data2_ARLEN = grp_conv2_fu_72_m_axi_WEIGHT_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data2_ARLEN = grp_conv1_fu_50_m_axi_WEIGHT_ARLEN;
    end else begin
        data2_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data2_ARLOCK = grp_conv2_fu_72_m_axi_WEIGHT_ARLOCK;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data2_ARLOCK = grp_conv1_fu_50_m_axi_WEIGHT_ARLOCK;
    end else begin
        data2_ARLOCK = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data2_ARPROT = grp_conv2_fu_72_m_axi_WEIGHT_ARPROT;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data2_ARPROT = grp_conv1_fu_50_m_axi_WEIGHT_ARPROT;
    end else begin
        data2_ARPROT = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data2_ARQOS = grp_conv2_fu_72_m_axi_WEIGHT_ARQOS;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data2_ARQOS = grp_conv1_fu_50_m_axi_WEIGHT_ARQOS;
    end else begin
        data2_ARQOS = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data2_ARREGION = grp_conv2_fu_72_m_axi_WEIGHT_ARREGION;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data2_ARREGION = grp_conv1_fu_50_m_axi_WEIGHT_ARREGION;
    end else begin
        data2_ARREGION = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data2_ARSIZE = grp_conv2_fu_72_m_axi_WEIGHT_ARSIZE;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data2_ARSIZE = grp_conv1_fu_50_m_axi_WEIGHT_ARSIZE;
    end else begin
        data2_ARSIZE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data2_ARUSER = grp_conv2_fu_72_m_axi_WEIGHT_ARUSER;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data2_ARUSER = grp_conv1_fu_50_m_axi_WEIGHT_ARUSER;
    end else begin
        data2_ARUSER = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data2_ARVALID = grp_conv2_fu_72_m_axi_WEIGHT_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data2_ARVALID = grp_conv1_fu_50_m_axi_WEIGHT_ARVALID;
    end else begin
        data2_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data2_RREADY = grp_conv2_fu_72_m_axi_WEIGHT_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data2_RREADY = grp_conv1_fu_50_m_axi_WEIGHT_RREADY;
    end else begin
        data2_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data3_ARADDR = grp_conv2_fu_72_m_axi_BIAS_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data3_ARADDR = grp_conv1_fu_50_m_axi_BIAS_ARADDR;
    end else begin
        data3_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data3_ARBURST = grp_conv2_fu_72_m_axi_BIAS_ARBURST;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data3_ARBURST = grp_conv1_fu_50_m_axi_BIAS_ARBURST;
    end else begin
        data3_ARBURST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data3_ARCACHE = grp_conv2_fu_72_m_axi_BIAS_ARCACHE;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data3_ARCACHE = grp_conv1_fu_50_m_axi_BIAS_ARCACHE;
    end else begin
        data3_ARCACHE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data3_ARID = grp_conv2_fu_72_m_axi_BIAS_ARID;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data3_ARID = grp_conv1_fu_50_m_axi_BIAS_ARID;
    end else begin
        data3_ARID = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data3_ARLEN = grp_conv2_fu_72_m_axi_BIAS_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data3_ARLEN = grp_conv1_fu_50_m_axi_BIAS_ARLEN;
    end else begin
        data3_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data3_ARLOCK = grp_conv2_fu_72_m_axi_BIAS_ARLOCK;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data3_ARLOCK = grp_conv1_fu_50_m_axi_BIAS_ARLOCK;
    end else begin
        data3_ARLOCK = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data3_ARPROT = grp_conv2_fu_72_m_axi_BIAS_ARPROT;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data3_ARPROT = grp_conv1_fu_50_m_axi_BIAS_ARPROT;
    end else begin
        data3_ARPROT = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data3_ARQOS = grp_conv2_fu_72_m_axi_BIAS_ARQOS;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data3_ARQOS = grp_conv1_fu_50_m_axi_BIAS_ARQOS;
    end else begin
        data3_ARQOS = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data3_ARREGION = grp_conv2_fu_72_m_axi_BIAS_ARREGION;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data3_ARREGION = grp_conv1_fu_50_m_axi_BIAS_ARREGION;
    end else begin
        data3_ARREGION = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data3_ARSIZE = grp_conv2_fu_72_m_axi_BIAS_ARSIZE;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data3_ARSIZE = grp_conv1_fu_50_m_axi_BIAS_ARSIZE;
    end else begin
        data3_ARSIZE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data3_ARUSER = grp_conv2_fu_72_m_axi_BIAS_ARUSER;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data3_ARUSER = grp_conv1_fu_50_m_axi_BIAS_ARUSER;
    end else begin
        data3_ARUSER = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data3_ARVALID = grp_conv2_fu_72_m_axi_BIAS_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data3_ARVALID = grp_conv1_fu_50_m_axi_BIAS_ARVALID;
    end else begin
        data3_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data3_RREADY = grp_conv2_fu_72_m_axi_BIAS_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data3_RREADY = grp_conv1_fu_50_m_axi_BIAS_RREADY;
    end else begin
        data3_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data_ARVALID = grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_ARVALID;
    end else begin
        data_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data_AWVALID = grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_AWVALID;
    end else begin
        data_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data_BREADY = grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_BREADY;
    end else begin
        data_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        data_RREADY = grp_conv1_fu_50_m_axi_FM_DDR_BUFF1_RREADY;
    end else begin
        data_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        data_WVALID = grp_conv2_fu_72_m_axi_FM_DDR_BUFF1_WVALID;
    end else begin
        data_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_conv1_fu_50_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_conv2_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_conv1_fu_50_ap_start = grp_conv1_fu_50_ap_start_reg;

assign grp_conv2_fu_72_ap_start = grp_conv2_fu_72_ap_start_reg;

endmodule //conv_top
